# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico    

# Content configuration version
version: 2

# Personal info
name: Priscila Jazmín Zavala Santoyo
title: Computer Engineering Student
email: priscila.zavala4323@alumnos.udg.mx
website: https://github.com/PriscilaJZavala

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: facespics
github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: priscilazvla
linkedin_username: linkedin.com/in/priscila-jazmín-zavala-santoyo-a0a1ba308
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/circulo.jpg
about_content: | # this will include new lines to allow paragraphs
  I am an enthusiastic person, eager to learn and gain new knowledge. I enjoy working in a team and taking on leadership roles, but I also know how to listen and follow instructions. I am willing to face new challenges and explore new learning paths.


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: WEB APPLICATION DESIGN
        link: github.com/PriscilaJZavala
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This would be the first web design project I created.
        description: | # this will include new lines to allow paragraphs
          For my final project, I developed a website that enables users to view products available for sale, log in as users, and register employees and products. The application was built using HTML, JavaScript, and PHP, with MySQL as the database.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Casa Guerrero Departamental
        link: :)
        # link_text: :).
        sub_title: Scholarship holder
        caption: 2022 - 
        quote: >
          Maintenance and documentation
        description: | # this will include new lines to allow paragraphs
            I worked for 3 months in the Systems department at the "Casa Guerrero" department store. My tasks included wiring different areas, creating documentation, and giving talks about cybersecurity and scams.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UNIVERSIDAD DE GUADALAJARA
        caption: Graduating in August 2025
        sub_title: Bachelor of computer engineering.
        quote: >
          The Centro Universitario de Ciencias Exactas e Ingenierías, CUCEI, is one of the thematic centers that make up the University Network of Jalisco.
        description: | # this will include new lines to allow paragraphs
          During my stay at CUCEI I have learned and acquired a lot of knowledge, as well as skills that lead to teamwork and meeting tight deadlines.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Along with my interests in networking and software engineering, some of my other interests and hobbies are:

      -Drawing.
      -Listening to music.
      -Working out.


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
